---
- name: create /etc/resolv.conf
  template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
  delegate_to: "{{ inventory_hostname }}"

- name: configure network interfaces
  template:
    src: "interfaces.j2"
    dest: "/etc/network/interfaces"

- name: configure /etc/hosts
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
