---
- name: Configure apt sources
  template: src=sources.list.j2 dest=/etc/apt/sources.list
#  notify:
#    - update_apt_sources
#  ^ commented out since the 'essential' role in the same play already forces an update
