---
- name: install packages
  apt:
    name: "{{ package }}"
    state: present
    update_cache: no
    install_recommends: no
  with_items: "{{ packages }}"
  loop_control:
    loop_var: package

- name: set hostname
  copy:
    content: "{{ inventory_hostname }}\n"
    dest: "/etc/hostname"

- name: create /var/log/journal for persistent systemd journal (takes effect after reboot)
  file:
    dest: /var/log/journal
    state: directory
