---
- name: install packages
  apt: name={{ item }} state=present update_cache=no install_recommends=no
  with_items: "{{ packages }}"

- name: create MySQL data directory
  file: path="{{ mysql_datadir }}" state=directory owner=mysql group=mysql mode=0700

- name: create MySQL binlog directory
  file: path="/srv/mysql-binlog" state=directory owner=mysql group=mysql mode=0700

- name: configure mysql
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify:
    - restart_mysql

- name: set MySQL root password
  mysql_user: name=root check_implicit_admin=yes login_user=root login_password="{{ lookup('file', './secure/groups/{{ mirror_hostgroup }}/mysql_password_root') }}" password="{{ lookup('file', './secure/groups/{{ mirror_hostgroup }}/mysql_password_root') }}"

- name: create /root/.my.cnf
  template: src=root_my.cnf.j2 dest=/root/.my.cnf mode=0600
