---
- name: Generate local ssh_config
  template: src=ssh_config.j2 dest=./ssh_config

# Note: There's also a 'known_hosts' Ansible module but it doesn't work well at
# the time of writing (always reports changes even when no new hosts are added).
# TODO: Figure out which public key(s) to include rather than only using ECDSA
# TODO: Add multiple hostname/IP variants for the same host
- name: Set local ssh_known_hosts
  lineinfile: dest="./ssh_known_hosts" regexp="^{{ item }} " line="{{ item }} {{ lookup('file', './files/hosts/{{ item }}/ssh_host_ecdsa_key.pub') }}" create=yes
  with_items: "{{ groups.servers }}"

